### ISSUE TITLE
OSX compatibility

### ISSUE THREAD

**Issue by tecjam** [costela/docker-etchosts#4]
Hi, first off i'd like to say a huge thank for this project. Works great on Linux and makes developing a lot easier.

Unfortunately this does not seem to work on Mac OSX, the problem being:

```
 level=error msg="error syncing hosts: could not open /etc/hosts for reading: open /etc/hosts: operation not permitted"
```

Is there any way to make it mac compatible in future?

**Comment by costela** [comment]
Hi @tecjam!

The problem with OSX is unfortunately a bit more structural: under OSX docker runs on a VM, and AFAIK does not expose the individual pods' network stack to the OSX host (see [here](https://docs.docker.com/desktop/mac/networking/#i-cannot-ping-my-containers)). So even if you could update `/etc/hosts`, the IPs it would point to would not be reachable.

Sorry this little project can't be more helpful in your case! :disappointed:
